In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np 

%matplotlib inline
pd.options.display.max_columns = 32
pd.options.display.max_rows = 200

In [2]:
PROJECT_ROOT_PATH = "../../"

datapath = PROJECT_ROOT_PATH + "lab_competition/data/"
outpath = PROJECT_ROOT_PATH + "lab_competition/output/01/"

import numpy as np
import collections

In [3]:
import re

# 各データを読み込みリストに格納
def read_file(path):
    with open(path, mode="r") as f:
        result = f.read().splitlines()
    return result

train_text = read_file(datapath + "text.train.txt")
dev_text = read_file(datapath + "text.dev.txt")
test_text = read_file(datapath + "text.test.txt")
train_label = np.loadtxt(datapath + "label.train.txt")
dev_label = np.loadtxt(datapath + "label.dev.txt")

# ラベル作成

In [4]:
def negaposi_3class(label_list):
    result = []
    for l in label_list:
        if l >= 1:
            result.append(1)
        elif l <= -1:
            result.append(-1)
        else:
            result.append(0)
    return result

def negative_2class(label_list):
    result = []
    for l in label_list:
        if l == -2:
            result.append(-2)
        elif l == -1:
            result.append(-1)
        else:
            result.append(0)
    return result

def positive_2class(label_list):
    result = []
    for l in label_list:
        if l == 2:
            result.append(2)
        elif l == 1:
            result.append(1)
        else:
            result.append(0)
    return result

In [5]:
train_df = pd.DataFrame()
train_df["data"] = train_label
train_df["3class"] = negaposi_3class(train_label)
train_df["positive"] = positive_2class(train_label)
train_df["negative"] = negative_2class(train_label)
train_df["text"] = train_text

print(train_df.head(50))

    data  3class  positive  negative  \
0    0.0       0         0         0
1    1.0       1         1         0
2    0.0       0         0         0
3    0.0       0         0         0
4    0.0       0         0         0
5    0.0       0         0         0
6    1.0       1         1         0
7    0.0       0         0         0
8    0.0       0         0         0
9    0.0       0         0         0
10  -1.0      -1         0        -1
11   0.0       0         0         0
12  -1.0      -1         0        -1
13   0.0       0         0         0
14   1.0       1         1         0
15   0.0       0         0         0
16   0.0       0         0         0
17   0.0       0         0         0
18   1.0       1         1         0
19   1.0       1         1         0
20   2.0       1         2         0
21   2.0       1         2         0
22   0.0       0         0         0
23   0.0       0         0         0
24  -1.0      -1         0        -1
25   0.0       0         0         0
26   0.0       0         0         0
27   1.0       1         1         0
28   0.0       0         0         0
29   2.0       1         2         0
30   0.0       0         0         0
31   0.0       0         0         0
32   0.0       0         0         0
33  -1.0      -1         0        -1
34   0.0       0         0         0
35  -1.0      -1         0        -1
36   0.0       0         0         0
37   0.0       0         0         0
38   1.0       1         1         0
39   0.0       0         0         0
40   0.0       0         0         0
41   2.0       1         2         0
42   1.0       1         1         0
43   1.0       1         1         0
44   0.0       0         0         0
45   0.0       0         0         0
46   0.0       0         0         0
47   0.0       0         0         0
48  -1.0      -1         0        -1
49   1.0       1         1         0

                                                 text
0                      ぼけっとしてたらこんな時間。チャリあるから食べにでたいのに…
1   今日の月も白くて明るい。昨日より雲が少なくてキレイな〜 と立ち止まる帰り道。チャリなし生活も...
2                  早寝するつもりが飲み物がなくなりコンビニへ。ん、今日、風が涼しいな。
3                                            眠い、眠れない。
4     ただいま〜 って新体操してるやん!外食する気満々で家に何もないのに!テレビから離れられない…!
5                                    表情筋が衰えてきてる。まずいな…
6               やばい。おもろいな〜思ってみてみた「シャレードがいっぱい」。よすぎるやん。
7                                     おなかすいた…夜ご飯仲間募集。
8                               よく寝た。暴走バスの夢見た。からだいたい。
9   最近アップにしていたので気づかなかったけど、ちゃんとブローしたらモテキ小宮山夏樹(後期)に似...
10  月末ミーティング終了。いつものことだが自分のミーティング力のなさに凹む。もう走り出すしかない...
11                  COWCOWヨシ君の顔色が最近ずっと悪い。病気ちゃうん?心配やわ。
12                                         シャンプーいきたい…
13  BIGBANGの人がえみちゃんねるにでてた。今、水泳の立石が…似すぎ。どちらも、生半可に喋り...
14  久々に自炊した。最近すごくやせたと評判なので、ごはんがすすむおかずをたんと。二膳半たべた。よしっ!
15                                              雨…（笑）
16       外反母趾が悪化。なぜ?ヒール止めてるし幅広い靴しか履いてないのに。本格的に治療すっかな。
17                 待ち人は来ないのではないかという疑念がふとよぎる。涼しくなったなぁ。
18  昔夢を語った仲間と数年ぶりの再会!相変わらず、だったけど少し大人になっていた僕ら、だった。そ...
19  みんな幸せになったらいいなって、なんか普通にそう思う。日曜と月曜と火曜会った人たちありがとう...
20       回鍋肉を作るつもりで何か違うやつになった。でもウマい!ウマすぎるぜ回鍋肉じゃないやつ!!
21  朝はパンケーキとサンドイッチ、昼はお弁当とサンドイッチ、夜は回鍋肉とごはんとパンケーキ。昨日...
22                                  天地明察みたいな〜おもろいんかな?
23  不確かな夜風が待ち人連れ去りぬ。−−−ふと、待ち人は来ないのではないかという疑念に駆られる。...
24  投げかけたものは返ってくるので、なるべく良いものを投げていたいと思う。しかし時には叶わないこ...
25    肉まん、サーモンロール、茶碗蒸し、納豆、シナモンロール。暇やからって食べ過ぎた…(●´з｀●)
26                                次の月曜の19時から落語観たい人〜??
27                                   ヤバい!2700のBO0WY!!
28                          最強の二人、夢売る二人、愛と誠。観たい映画、メモ…
29  ごくありきたりで俗っぽくて申し訳ないのですが、ミランダ・カーめっちゃ可愛い!めっちゃ好き!い...
30  腰をイワしています。痛み止め飲んでるからか四六時中眠い。いける日は整骨院でほぐしてもらうけど...
31                                落語…どしよかな…それか映画いこかな。
32  結局映画にも落語にも整体にも行けず、せめて夕飯はと思ったのに怠けグセがついて、出前とってしま...
33                                          眠いのに眠れない…
34                        今日のアボカドはあじひとで食べるかな!誰か釣れるかな!
35  自己否定感が強い人は他人も否定する。批判の多いのは、自分に自信がないと宣伝しているようなもの...
36  今日カラーをしてもらったら鬼太郎ぽくなった。仕事帰りに会った数名の知人にはいいやん!と言って...
37                                      鬼太郎ぽい体型の女子って…
38  うどんとラーメンハシゴしておなかパンパン!初、丸亀製麺からの彦ェ門!あっさりとんこつで完食!...
39                                        なすの田楽食べたいな〜
40                          ご飯食べにいきたい…でも、もう眠いよパトラッシュ…
41  腰が痛い日々を送っています。色んなことが段々面倒になってきた。昨日の晩から数えて初めての食事...
42  天王寺ぶらり。あわよくば映画みてやろ〜!程よくおなかも空いてきたし、一人でもいけそーないい感...
43               こんな時間に鴨つけうどん!ゆずピール入ってて結構おいしい!やるななか卯。
44  経済ジャーナリスト金子さん(ほんまでっか出演)の訃報にびっくり。病気みたい。ご冥福をお祈りい...
45          何でもないようなことが幸せだったと思う〜何でもない夜のこと、腰痛で寝れないよーる〜
46  少し前から毎日のようにつきまとわれている。姿が見えない日もあって油断してるときっちり現れて、...
47                      腰痛の話。寝てもさめても腰痛い。痛みよ、去れ!イたとん!!
48                 メルヘンに憧れがち。現実を生きなければな。てか早く寝たい(>_<)!
49                  今週も終わった!そして今から休みだ!明日は祝日か〜何しよどこいこ!

In [6]:
train_df.groupby('3class').describe()

           data                                              positive  \
          count      mean       std  min  25%  50%  75%  max    count
3class
-1       9136.0 -1.387806  0.487277 -2.0 -2.0 -1.0 -1.0 -1.0   9136.0
 0       9227.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0   9227.0
 1      11637.0  1.333161  0.471364  1.0  1.0  1.0  2.0  2.0  11637.0

                                                    negative            \
            mean       std  min  25%  50%  75%  max    count      mean
3class
-1      0.000000  0.000000  0.0  0.0  0.0  0.0  0.0   9136.0 -1.387806
 0      0.000000  0.000000  0.0  0.0  0.0  0.0  0.0   9227.0  0.000000
 1      1.333161  0.471364  1.0  1.0  1.0  2.0  2.0  11637.0  0.000000


             std  min  25%  50%  75%  max
3class
-1      0.487277 -2.0 -2.0 -1.0 -1.0 -1.0
 0      0.000000  0.0  0.0  0.0  0.0  0.0
 1      0.000000  0.0  0.0  0.0  0.0  0.0

In [7]:
train_df.groupby('positive').describe()

             data                                                3class  \
            count      mean       std  min  25%  50%  75%  max    count
positive
0         18363.0 -0.690465  0.774365 -2.0 -1.0  0.0  0.0  0.0  18363.0
1          7760.0  1.000000  0.000000  1.0  1.0  1.0  1.0  1.0   7760.0
2          3877.0  2.000000  0.000000  2.0  2.0  2.0  2.0  2.0   3877.0

                                                      negative            \
              mean       std  min  25%  50%  75%  max    count      mean
positive
0        -0.497522  0.500007 -1.0 -1.0  0.0  0.0  0.0  18363.0 -0.690465
1         1.000000  0.000000  1.0  1.0  1.0  1.0  1.0   7760.0  0.000000
2         1.000000  0.000000  1.0  1.0  1.0  1.0  1.0   3877.0  0.000000


               std  min  25%  50%  75%  max
positive
0         0.774365 -2.0 -1.0  0.0  0.0  0.0
1         0.000000  0.0  0.0  0.0  0.0  0.0
2         0.000000  0.0  0.0  0.0  0.0  0.0

In [8]:
train_df.groupby('negative').describe()

             data                                                3class  \
            count      mean       std  min  25%  50%  75%  max    count
negative
-2         3543.0 -2.000000  0.000000 -2.0 -2.0 -2.0 -2.0 -2.0   3543.0
-1         5593.0 -1.000000  0.000000 -1.0 -1.0 -1.0 -1.0 -1.0   5593.0
 0        20864.0  0.743577  0.749895  0.0  0.0  1.0  1.0  2.0  20864.0

                                                      positive            \
              mean       std  min  25%  50%  75%  max    count      mean
negative
-2       -1.000000  0.000000 -1.0 -1.0 -1.0 -1.0 -1.0   3543.0  0.000000
-1       -1.000000  0.000000 -1.0 -1.0 -1.0 -1.0 -1.0   5593.0  0.000000
 0        0.557755  0.496665  0.0  0.0  1.0  1.0  1.0  20864.0  0.743577


               std  min  25%  50%  75%  max
negative
-2        0.000000  0.0  0.0  0.0  0.0  0.0
-1        0.000000  0.0  0.0  0.0  0.0  0.0
 0        0.749895  0.0  0.0  1.0  1.0  2.0

In [9]:
train_df.to_csv(datapath+"train_3class.csv", columns=["3class", "text"], index = False)
train_df[train_df["3class"] == 1].to_csv(datapath+"train_positive.csv", columns=["positive", "text"], index = False)
train_df[train_df["3class"] == -1].to_csv(datapath+"train_negative.csv", columns=["negative", "text"], index = False)

### devデータ

In [10]:
dev_df = pd.DataFrame()
dev_df["data"] = dev_label
dev_df["3class"] = negaposi_3class(dev_label)
dev_df["positive"] = positive_2class(dev_label)
dev_df["negative"] = negative_2class(dev_label)
dev_df["text"] = dev_text

print(dev_df.head(50))

    data  3class  positive  negative  \
0    0.0       0         0         0
1   -2.0      -1         0        -2
2   -1.0      -1         0        -1
3    0.0       0         0         0
4   -1.0      -1         0        -1
5   -1.0      -1         0        -1
6    2.0       1         2         0
7    0.0       0         0         0
8   -1.0      -1         0        -1
9   -1.0      -1         0        -1
10   0.0       0         0         0
11   0.0       0         0         0
12  -1.0      -1         0        -1
13  -1.0      -1         0        -1
14   0.0       0         0         0
15   2.0       1         2         0
16   2.0       1         2         0
17   2.0       1         2         0
18   2.0       1         2         0
19   2.0       1         2         0
20   2.0       1         2         0
21   2.0       1         2         0
22   2.0       1         2         0
23   2.0       1         2         0
24   2.0       1         2         0
25   2.0       1         2         0
26   1.0       1         1         0
27   0.0       0         0         0
28   0.0       0         0         0
29   0.0       0         0         0
30   0.0       0         0         0
31  -1.0      -1         0        -1
32  -2.0      -1         0        -2
33  -1.0      -1         0        -1
34   0.0       0         0         0
35   0.0       0         0         0
36   2.0       1         2         0
37   2.0       1         2         0
38   2.0       1         2         0
39   2.0       1         2         0
40   0.0       0         0         0
41   2.0       1         2         0
42   2.0       1         2         0
43   2.0       1         2         0
44   2.0       1         2         0
45   0.0       0         0         0
46   0.0       0         0         0
47   0.0       0         0         0
48   2.0       1         2         0
49   2.0       1         2         0

                                                 text
0                             建設中の建物の利用目的も変更になるだろうなあ。
1                演劇とかも同時並行でやっている。演劇の危機にどう思ってるか知りたかった。
2              犬夜叉には腐女子っていないのかな？というかあの漫画はＮＬ向けの漫画なのかも。
3           話を続けるための子どもって感じかな。でも、それって簡単にやってはいけない気もする。
4                           今、製作中の劇場版が子どもとかだったらどうしよう。
5               終わってから勝手に子どもとかは今の時代に厳しいよねー銀魂だったらショック。
6   銀魂はあの終わり方は全ての界隈で大変、評価されていて、そういう意味での空知先生、ありがとう連...
7                          ジャンプの休載、終わってるからもはや関係なくて・・・
8                   年末まで見合わせって驚く決断だと思う。それなら紅白もダメじゃない？
9          こんな時だから？？知ってる人が何してるかが必要以上に気になるねー生存確認的な意味で。
10                                  フォローとかはあまりしたくないし、
11                                 紅白はたぶん出ないけど。例えとして。
12      私も影響はあるけど、1年ぐらいダメだと思い込んでる。というか・・・悪い方にしか浮かばない。
13                            あれもこれもＩＴ化すればいいってわけでもない。
14   いろいろ感想を持つけど、あとでこういうところに書く予定だと感想を持つ時点でそうなるからよくない。
15                                         曲の感想文を書いた。
16                  5年前に行ったミニシアターを調べた。営業再開だった。大丈夫みたい。
17                                         この時は1人で見た。
18             普通な一般的な人たちの話。まだ経験が浅い。腐女子4人でやってみたら面白そう。
19     無責任だけど、劇もライブもやっていいのでは。。行く人の基準は持病があるかないかも重要と思う。
20                         昨日ステイゴールドを聞いた。久しぶりのように思った。
21                        37分30歳に賢人は5年も廃墟を徘徊。40分まで見た。
22  ドラマや映画でなく一度、舞台の演技を観てみたかったから・・・見てよかったと思う。舞台ってＤＶ...
23          岡田将生 結婚で検索したら岡田将生 さんは結婚されてませんって表示された。面白い。
24      岡田将生 結婚 子供岡田将生 結婚してるとかでもよく検索されている。岡田将生 今もあった。
25                       色んな名前と一緒に結婚も多い。岡田将生 Aさん 結婚とか
26         ガッキーとはもう結婚しないだろうな。星野源と同じマンションに住んでるから進展あった？
27               結婚ネタは避けたいけど攻めてみた。どうでもいい。宇宙の外でやってほしい。
28                                         よくわからない連携。
29                         振り返り、去年の今頃、アプリ連載の1話目だったっけ？
30                             2019年5月13日月曜日が702訓だった。
31                                       この3年が無駄になった。
32                                         空気を読んでなくて。
33  自分がその名を口にしていいレベルじゃないのにやってしまったのが間違えか。すごい学歴とか職歴と...
34  すべてが勘違いで終わりそう。最近、知ったあの人も知ってるのかな？ならうれしいとかずっと考えて...
35                                      っていうか、英語の聞きすぎ
36             なのかも。思い込んだら、重いコンダラみたいなのもあるらしい。小槍の上、コヤギ
37  勘違い祭り。歌詞の勘違い多い。空耳。単純な動詞なのにそんな重要なところにいるのか！みたいな驚...
38                                  人は思ってるより自由ですってこと。
39                               3文字なら間違えはないのかなって悩み中。
40                    さっき、雨の中、急に混線してきた宇多田ヒカルに負けてしまった。
41  絶対にこの日に一瞬、迷ったけど、決めた。イベントに参加する。家にいながらにおいても、いついつ...
42                    2014年も記念の年で、いつも記念日を数えているみたいですごい
43  レンタルの予約。今度は去年、大人気の洋画を。そんなに人気あったっけ？的にどれも貸し出し中に。...
44       無期限にだらだらと借りれるところだけが最大のメリットすぎる。今回も丸々1ヶ月も借りてた。
45           5月から大衆演劇だけ再開する動き。広告もあった。他は自主判断で中止の発表が多い。
46                      長崎県も同じ。16日から営業可能って小さく新聞に載ってた。
47                                        福岡、大阪は×だった。
48  全部見た。特にオチはなかった。面白そうな展開もあったんだけど・・・人が人としゃべっているのが...
49                                        7ヵ月前のコメあった。

In [11]:
dev_df.to_csv(datapath+"dev_3class.csv", columns=["3class", "text"], index = False)
dev_df[train_df["3class"] == 1].to_csv(datapath+"dev_positive.csv", columns=["positive", "text"], index = False)
dev_df[train_df["3class"] == -1].to_csv(datapath+"dev_negative.csv", columns=["negative", "text"], index = False)

/tmp/ipykernel_3403/1410895442.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dev_df[train_df["3class"] == 1].to_csv(datapath+"dev_positive.csv", columns=["positive", "text"], index = False)
/tmp/ipykernel_3403/1410895442.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dev_df[train_df["3class"] == -1].to_csv(datapath+"dev_negative.csv", columns=["negative", "text"], index = False)

# テストデータ csv出力

In [12]:
test_df = pd.DataFrame()
test_df["text"] = test_text

test_df.to_csv(datapath+"step_estimator_tmp.csv", columns=["text"], index = False)

# Devデータ 集計用csv出力

In [13]:
dev_df.to_csv(datapath+"step_estimator_dev_tmp.csv", columns=["data", "text"], index = False)